# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.filePathLabel = QtWidgets.QLabel(Form)
        self.filePathLabel.setGeometry(QtCore.QRect(140, 70, 91, 61))
        self.filePathLabel.setObjectName("filePathLabel")
        self.statusLabel = QtWidgets.QLabel(Form)
        self.statusLabel.setGeometry(QtCore.QRect(150, 150, 111, 20))
        self.statusLabel.setObjectName("statusLabel")
        self.selectFileButton = QtWidgets.QPushButton(Form)
        self.selectFileButton.setGeometry(QtCore.QRect(20, 220, 93, 28))
        self.selectFileButton.setObjectName("selectFileButton")
        self.convertButton = QtWidgets.QPushButton(Form)
        self.convertButton.setGeometry(QtCore.QRect(290, 220, 93, 28))
        self.convertButton.setObjectName("convertButton")
        self.conversionComboBox = QtWidgets.QComboBox(Form)
        self.conversionComboBox.setGeometry(QtCore.QRect(130, 20, 131, 22))
        self.conversionComboBox.setObjectName("conversionComboBox")
        self.conversionComboBox.addItem("")
        self.conversionComboBox.addItem("")
        self.conversionComboBox.addItem("")
        self.conversionComboBox.addItem("")
        self.conversionComboBox.addItem("")
        self.conversionComboBox.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.filePathLabel.setText(_translate("Form", "No file selected"))
        self.statusLabel.setText(_translate("Form", "status"))
        self.selectFileButton.setText(_translate("Form", "Select File"))
        self.convertButton.setText(_translate("Form", "Convert"))
        self.conversionComboBox.setItemText(0, _translate("Form", "PDF to Word"))
        self.conversionComboBox.setItemText(1, _translate("Form", "Word to PDF"))
        self.conversionComboBox.setItemText(2, _translate("Form", "Excel to Word"))
        self.conversionComboBox.setItemText(3, _translate("Form", "Image to PDF"))
        self.conversionComboBox.setItemText(4, _translate("Form", "Image Text Extract"))
        self.conversionComboBox.setItemText(5, _translate("Form", "Text to Audio"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
